// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowExample.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Simple Messaging")]
    public partial class SimpleMessagingFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OneToOneMessaging.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Simple Messaging", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Simple message exchange")]
        public virtual void SimpleMessageExchange()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Simple message exchange", null, ((string[])(null)));
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "User"});
            table6.AddRow(new string[] {
                        "Johnny"});
            table6.AddRow(new string[] {
                        "Benjamin"});
#line 4
testRunner.Given("the following users:", ((string)(null)), table6, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "From",
                        "To",
                        "Text"});
            table7.AddRow(new string[] {
                        "Johnny",
                        "Benjamin",
                        "Hello!"});
            table7.AddRow(new string[] {
                        "Benjamin",
                        "Johnny",
                        "Hi!"});
            table7.AddRow(new string[] {
                        "Johnny",
                        "Benjamin",
                        "What\'s up?"});
            table7.AddRow(new string[] {
                        "Benjamin",
                        "Johnny",
                        "Nothing."});
#line 8
 testRunner.When("they send the following messages in order:", ((string)(null)), table7, "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "From",
                        "Text"});
            table8.AddRow(new string[] {
                        "Me",
                        "Hello!"});
            table8.AddRow(new string[] {
                        "Benjamin",
                        "Hi!"});
            table8.AddRow(new string[] {
                        "Me",
                        "What\'s up?"});
            table8.AddRow(new string[] {
                        "Benjamin",
                        "Nothing."});
#line 14
 testRunner.Then("Johnny should see:", ((string)(null)), table8, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "From",
                        "Text"});
            table9.AddRow(new string[] {
                        "Johnny",
                        "Hello!"});
            table9.AddRow(new string[] {
                        "Me",
                        "Hi!"});
            table9.AddRow(new string[] {
                        "Johnny",
                        "What\'s up?"});
            table9.AddRow(new string[] {
                        "Me",
                        "Nothing."});
#line 20
 testRunner.And("Benjamin should see:", ((string)(null)), table9, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
